# f=open('py','x')
# f.write('welcome to all')
# f.write('  to pyton')
# f=open('demo','w')
# f.write('welcome back')
# f.write(str(123))
# f.write(str([1,2,3,4,5]))
# f=open('demo','a')
# f.write(  'python')
n=int(input('Enter limit:'))
f=open('demo','w')
for i in range(n):
    name=input('Enter name:')
    f.write(name+'\n')