# s='malayalam is kerala language'
# print(s[0])
# print(s.capitalize())
# print(s.isupper())
# print(s.islower())
# print(s.lower())
# print(s.upper())
# print(s)
# print(s.strip())
# print(s.lstrip())
# print(s.rstrip())
# print(s.split(' '))
# print(s.startswith('m'))
# print(s.endswith('e'))
# print(s.index('k'))
# print(s.find('k'))
# print(s.center(20))
# a='123'
# print(a.isdigit())
# print("{:<20} {:<10} {:<20}".format('Name','Age','Place'))
# print("{:<20} {:<10} {:<20}".format('aa','21','kkm'))
# print('welcome \n ew')
# print(r'welcome \n ew')